print "%s" % (True and True)
print "%s" % (False and True)
print "%s" % (1 == 1 and 2 == 2)
print "%s" % ("test" == "test")
print "%s" % (1== 1 or 2 != 1)
print "%s" % (True and 1 == 1)
print "%s" % (False and 0 != 0)
print "%s" % (True or 1 == 1)
print "%s" % ("test" == "testing")
print "%s" % (1 != 0 and 2 == 1)
print "%s" % ("test" != "testing")
print "%s" % ("test" == 1)
print "%s" % (not (True and False))
print "%s" % (not (1 == 1 and 0 != 1))
print "%s" % (not (10 == 1 or 1000 == 1000))
print "%s" % (not (1 != 10 or 3 == 4))
print "%s" % (not ("testing" == "testing" and "Zed" == "Cool Guy"))
print "%s" % (1 == 1 and not ("testing" == 1 or 1 == 0))
print "%s" % ("chunky" == "bacon" and not (3 == 4 or 3 == 3))
print "%s" % (3 == 3 and not ("testing" == "testing" or "python" == "Fun"))
raw_input("press enter to exit...")